import UIKit

//Critical Thinking Assignment: Candy Fundraiser Operators Program

let targetTotalCandyBars = 15_000 // Represents the total number of candy bars that the fundraiser needs to sell to meet their target goal.

let costOfEachCandyBar = 0.50 // Cost per candy bar

var totalCandyBarsSold = 0 // Total number of candy bars sold by both groups.

var soldByGroupTiger = 0 // Number of candy bars sold by Group Tiger.
var soldByGroupPurpleRain = 0 // Number of candy bars sold by Group PurpleRain.

var weeklyTotal = 0

var totalCandytoSell = 0 // assign a starting point to the variable

// Using Arithmetic & Compond assignment operators

// Week 1 of Candy Bar Fundraiser
soldByGroupTiger += 350 // Group Tiger sells 350 candy bars
soldByGroupPurpleRain += 450 // Group PurpleRain sells 450 candy bars.
weeklyTotal = soldByGroupTiger + soldByGroupPurpleRain

//Week 2 of Candy Bar Fundraiser
soldByGroupTiger += 1000 // Group Tiger sells an additional 1000 in week 2.
soldByGroupPurpleRain += 2000 // Group PurpleRain sells an 2000 candy bars in week 2.
weeklyTotal = soldByGroupTiger + soldByGroupPurpleRain

//Week 3 of Candy Bar Fundraiser
soldByGroupTiger += 3500 // Group Tiger week 3 sold.
soldByGroupPurpleRain += 4500 // Group PurpleRain week 3 sold.
weeklyTotal = soldByGroupTiger + soldByGroupPurpleRain

//Week 4 of Candy Bar Fundraiser
totalCandyBarsSold = soldByGroupTiger + soldByGroupPurpleRain
totalCandytoSell = targetTotalCandyBars - totalCandyBarsSold

soldByGroupTiger += 2200
soldByGroupPurpleRain += 998

weeklyTotal = soldByGroupTiger + soldByGroupPurpleRain
totalCandyBarsSold = weeklyTotal


// Calculate total revenue
let totalRevenue = Double(totalCandyBarsSold) * costOfEachCandyBar
let totalRevenueTigers = Double(soldByGroupTiger) * costOfEachCandyBar
let totalRevenuePurpleRain = Double(soldByGroupPurpleRain) * costOfEachCandyBar

// Calculate Percentage
let totalPercentTiger = Double(soldByGroupTiger) / Double(totalCandyBarsSold) * 100
let totalPercentPurpleRain = Double(soldByGroupPurpleRain) / Double(totalCandyBarsSold) * 100
let totalPercent = totalPercentTiger + totalPercentPurpleRain

// Candy Bars Remaining using the Remainder Operator
let totalCandyBarsLeft = targetTotalCandyBars % totalCandyBarsSold //


if totalPercent == 100 {
    print("The total percentage sold is 100%.")
} else {
    print("The total percentage does not add up to 100%.")
}
    
// Display the results
print("Group Tiger sold \(soldByGroupTiger) candy bars and made $ \(Int(totalRevenueTigers)).")
print("Group PurpleRain the winners sold \(Int(totalPercentPurpleRain)) % of our Candy Bar Inventory which was made up of \(soldByGroupPurpleRain) candy bars and made $ \(Int(totalRevenuePurpleRain)) dollars in Fundraising money.")
print("Total candy bars sold by all groups: \(totalCandyBarsSold)")
print("Total revenue generated by all groups: $\(totalRevenue)")
print("We only had \(totalCandyBarsLeft) Candy Bars Left!")

//Using Comparision Operator with if else statement
if soldByGroupTiger < soldByGroupPurpleRain {
    print("Congrats! Group PurpleRain are the winners!")
} else {
    print("Congrats! Group Tigers are the winners!")
}

//Using Comparision Operator
if totalCandyBarsLeft > 0 {
    print("We have some candy bars left")
}

